### ISSUE TITLE
release: 8.0rc1

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-admin#144]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Milestones for release**

- cylc-flow: [![](https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/74)](https://github.com/cylc/cylc-flow/milestone/74)
- cylc-uiserver: [![](https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/2)](https://github.com/cylc/cylc-uiserver/milestone/2)
- cylc-ui: [![](https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/3)](https://github.com/cylc/cylc-ui/milestone/3)
- cylc-rose: [![](https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/3)](https://github.com/cylc/cylc-rose/milestone/3)
- metomi/rose: [![](https://img.shields.io/github/milestones/issues-open/metomi/rose/64)](https://github.com/metomi/rose/milestone/64)
- cylc-doc: [![GitHub milestone](https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/1)](https://github.com/cylc/cylc-doc/milestone/1)

**Required for all minor releases of cylc-flow.**

Se [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md)
for first time instructions and more info.

#### Prep:

* [x] Ensure all milestones complete.
* [x] Test cylc-doc (run a test build, perform any required fixes).
* [x] Delete entries below for packages you are not releasing.

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.

* [x] cylc-flow
* [x] cylc-ui
* [x] cylc-uiserver (update the ui version before releasing)
* [x] metomi-rose 
* [x] cylc-rose **messed up, my bad, re-releasing as 1.0.1**

#### Forge (check dependencies match):

`noarch: python` changes:

* [x] [cylc-flow](https://github.com/conda-forge/cylc-flow-feedstock/pull/33) (released as new 8.0b3 build)
* [x] [cylc-uiserver](https://github.com/conda-forge/cylc-uiserver-feedstock/pull/22)
* [x] [cylc-rose](https://github.com/conda-forge/cylc-rose-feedstock/issues/4)
* [x] [metomi-rose](https://github.com/conda-forge/metomi-rose-feedstock/issues/8) (cannot be done *before* 2.0rc1 release)

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> If not, create a new branch, change the version, reset the build number and
> update the hash from the PyPi website.
> Finally trigger a rerender in a comment.

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

* [x] cylc-flow
* [x] cylc-uiserver
* [x] metomi-rose
* [x] cylc-rose **Do not release 1.0.0, only release 1.0.1**

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* cylc-doc
  * [x] bump instersphinx versions if required
  * [x] review installation instructions - https://github.com/cylc/cylc-doc/pull/408
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* [x] rose: build & deploy docs
* [x] discourse post
  * This time around we need to include a note to tell beta users the uiserver config path has changed from `hub/` to `uiserver/`.
  * https://cylc.discourse.group/t/cylc-8-0rc1-released/435
* [x] https://github.com/cylc/cylc-uiserver/issues/303

#### Metadata:

> Update project versions to the next milestone
> AND pin downstream components to the next cylc-flow dev release.

* [x] cylc-flow
* [x] cylc-uiserver (pin to latest cylc-flow)
* [x] cylc-rose (pin to latest cylc-flow)

#### Finally:

* [x] close this issue :rocket:

**Comment by MetRonnie** [comment]
I take it we're not doing the 2.1 release of isodatetime until next time?

**Comment by oliver-sanders** [comment]
Yes, no isodatetime release for RC1.

**Comment by MetRonnie** [comment]
> - [x] [cylc-flow](https://github.com/conda-forge/cylc-flow-feedstock/pull/33) (released as new 8.0rc3 build)

?

**Comment by oliver-sanders** [comment]
Running docs build against master on all projects: https://github.com/cylc/cylc-doc/runs/5217347937?check_suite_focus=true

**Comment by oliver-sanders** [comment]
cylc-flow functional/flaky tests passing for MacOS (CI only runs CHUNK=1/4)

**Comment by oliver-sanders** [comment]
Nasty UI regression spotted in the released 1.0.0 code https://github.com/cylc/cylc-ui/issues/930

**Comment by oliver-sanders** [comment]
(I made a mess of the cylc-rose metadata so we have had to re-release as 1.0.1)

**Comment by hjoliver** [comment]
cylc-uiserver now published to conda-forge

**Comment by oliver-sanders** [comment]
Conclusion of the Jinja2 issues with markupsafe.

* We have released a new RC1 "build" for cylc-flow on conda forge which upper-pins markupsafe so `conda install` will soon work fine.
* We will update the docs to change the instructions for pip installs.
* For the next release we will upper-pin markupsafe for pypi releases too.

**Comment by oliver-sanders** [comment]
(wait until the new cylc-flow build is published before releasing...)

**Comment by oliver-sanders** [comment]
All done, happy RC1.
