### ISSUE TITLE
release: 8.0rc2

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-admin#148]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] Ensure all milestones complete.
* [x] Test cylc-doc (run a test build, perform any required fixes). https://github.com/cylc/cylc-doc/actions/runs/2023367714
* [x] Run cylc-flow functional tests against locally available platforms.
* [x] List the milestones for release below (delete entries as appropriate).

#### Non-bumpable PRs
- [x] https://github.com/cylc/cylc-rose/pull/120 & https://github.com/metomi/rose/pull/2557
- [x] https://github.com/metomi/rose/pull/2555
- [x] https://github.com/cylc/cylc-flow/pull/4733

#### Milestones for release:

- cylc-flow: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/97)](
  https://github.com/cylc/cylc-flow/issues?q=is%3Aopen+milestone%3Acylc-8.0rc2)
- cylc-ui: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/11)](
  https://github.com/cylc/cylc-ui/milestone/11)
- cylc-uiserver: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/10)](
  https://github.com/cylc/cylc-uiserver/milestone/10)
- metomi/rose: [![](
  https://img.shields.io/github/milestones/issues-open/metomi/rose/78)](
  https://github.com/metomi/rose/milestone/78)
- cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/9)](
  https://github.com/cylc/cylc-rose/milestone/9)
- cylc-doc: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/5)](
  https://github.com/cylc/cylc-doc/milestone/5)

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.

* [x] metomi-isodatetime
* [x] cylc-flow (bump metomi-isodatetime if required)
* [x] cylc-ui
* [x] cylc-uiserver ([update the ui](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) version before releasing)
* [x] metomi-rose (bump metomi-isodatetime if required)
* [x] cylc-rose

#### Forge (check dependencies match):

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> If not, create a new branch, change the version, reset the build number and
> update the hash from the PyPi website.
> Finally trigger a rerender in a comment.

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

* [x] cylc-flow
* [x] cylc-ui
* [x] cylc-uiserver
* [x] metomi-rose
* [x] cylc-rose

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* cylc-doc
  * [x] bump instersphinx versions if required
  * [x] review installation instructions
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* metomi-rose
  * [x] build & deploy documentation (manual process ATM)
* [x] discourse post

#### Metadata:

> Update project versions to the next milestone
> AND pin downstream components to the next cylc-flow dev release.

* [x] cylc-flow
* [x] cylc-uiserver (pin to latest cylc-flow)
* [x] cylc-rose (pin to latest cylc-flow)

#### Finally:

* [x] close this issue :rocket:
