### ISSUE TITLE
8.0.0

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-admin#157]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] Ensure all milestones complete.
* [x] Test cylc-doc (run a test build, perform any required fixes).
* [x] Run cylc-flow functional tests against locally available platforms.
* [x] List the milestones for release below (delete entries as appropriate).

#### Milestones for release:

> The release actions close the milestones for you automatically.

- cylc-flow: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/95)](
  https://github.com/cylc/cylc-flow/milestone/95)
- cylc-ui: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/14)](
  https://github.com/cylc/cylc-ui/milestone/14)
- cylc-uiserver: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/9)](
  https://github.com/cylc/cylc-uiserver/milestone/9)
- metomi/rose: [![](
  https://img.shields.io/github/milestones/issues-open/metomi/rose/77)](
  https://github.com/metomi/rose/milestone/77)
- cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/11)](
  https://github.com/cylc/cylc-rose/milestone/11)
- cylc-doc: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/4)](
  https://github.com/cylc/cylc-doc/milestone/4)

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.
>
> <details>
>   <summary>(logical release order)</summary>
> <pre>R1 = """
>    cylc_flow & metomi_rose => cylc_rose
>    cylc_flow & cylc_ui => cylc_uis
> """</pre>
> </details>

> <details>
>   <summary>Info on version pinning</summary>
>   <br />
>   Cylc plugins (i.e. cylc-rose and cylc-uiserver) are "pinned" to the minor version
>   of cylc-flow. E.G. if the cylc-flow version is 8.1.2 the plugins should be pinned to 8.1.
>   <br /><br />
>   <a href="https://github.com/cylc/cylc-admin/issues/130">More Information</a>
> </details>

* [x] cylc-flow
* [x] cylc-ui
* [x] cylc-uiserver (update the ui [via GH action](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) first)
* [x] metomi-rose
* [x] cylc-rose
* [x] cylc-sphinx-extensions

#### Forge (check dependencies match):

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> <details>
>   <summary>If the PR doesn't get opened automatically</summary>
>   <br />Create a new branch, change the version, reset the build number and
>   update the hash from the PyPi website.
>   <br />Finally trigger a rerender in a comment.
> </details>

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

* [x] cylc-flow
* [x] ~cylc-ui (decide if "dead-ending" or what)~ later
* [x] cylc-uiserver
* [x] metomi-rose
* [x] cylc-rose

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* cylc-doc
  * [x] bump intersphinx versions if required (`cylc-doc/src/conf.py`)
  * [x] review [deployment instructions](https://github.com/cylc/cylc-doc#deploying)
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* metomi-rose
  * [x] build & deploy documentation (manual process ATM)
* [x] discourse post

#### Metadata:

> Update project versions to the next milestone
> AND pin downstream components to the next cylc-flow dev release.

* [x] cylc-flow
* [x] cylc-uiserver (pin to latest cylc-flow)
* [x] cylc-rose (pin to latest cylc-flow)
* [x] metomi-rose

#### Finally:

* [ ] close this issue :rocket:

**Comment by oliver-sanders** [comment]
* [ ] nice to have fix for the docs in [cylc-sphinx-extensions](https://github.com/cylc/cylc-sphinx-extensions/pull/71)
