### ISSUE TITLE
Cylc Rose Release 1.1.1

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-admin#158]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] Ensure all milestones complete.
* [ ] Test cylc-doc (run a test build, perform any required fixes).
* [ ] Run cylc-flow functional tests against locally available platforms.
* [ ] List the milestones for release below (delete entries as appropriate).

#### Milestones for release:

> The release actions close the milestones for you automatically.

- cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/<number>)](
  https://github.com/cylc/cylc-rose/milestone/<number>)

#### PyPi / GitHub releases:

> Trigger releases via GitHub actions.

#### Forge (check dependencies match):

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.
> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* [ ] cylc-rose (pin to latest cylc-flow)

#### Finally:

* [ ] close this issue :rocket:
