### ISSUE TITLE
release: 8.1.0

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-admin#162]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] Ensure all milestones complete.
* [x] Ensure major changes are listed in cylc-doc (`reference/changes`).
* [x] Test cylc-doc (run a test build, perform any required fixes).
* [x] Run cylc-flow functional tests against locally available platforms.
* [x] List the milestones for release below (delete entries as appropriate).

#### Milestones for release:

> The release actions close the milestones for you automatically.

- cylc-flow: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/99)](
  https://github.com/cylc/cylc-flow/milestone/99)
- cylc-ui: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/15)](
  https://github.com/cylc/cylc-ui/milestone/15)
- cylc-uiserver: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/16)](
  https://github.com/cylc/cylc-uiserver/milestone/16)
- cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/7)](
  https://github.com/cylc/cylc-rose/milestone/7)
- cylc-doc: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/8)](
  https://github.com/cylc/cylc-doc/milestone/8)

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.
>
> <details>
>   <summary>(logical release order)</summary>
> <pre>R1 = """
>    cylc_flow & metomi_rose => cylc_rose
>    cylc_flow & cylc_ui => cylc_uis
> """</pre>
> </details>

> <details>
>   <summary>Info on version pinning</summary>
>   <br />
>   Cylc plugins (i.e. cylc-rose and cylc-uiserver) are "pinned" to the minor version
>   of cylc-flow. E.G. if the cylc-flow version is 8.1.2 the plugins should be pinned to 8.1.
>   <br /><br />
>   <a href="https://github.com/cylc/cylc-admin/issues/130">More Information</a>
> </details>

* [x] ~metomi-isodatetime~
* [x] cylc-flow (bump metomi-isodatetime if required)
* [x] cylc-ui
* [x] cylc-uiserver ([update the ui [via GH action](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) first)
* [x] ~metomi-rose (bump metomi-isodatetime if required)~
* [x] cylc-rose

#### Forge (check dependencies match):

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> <details>
>   <summary>If the PR doesn't get opened automatically</summary>
>   <br />Create a new branch, change the version, reset the build number and
>   update the hash from the PyPi website.
>   <br />Finally trigger a rerender in a comment.
> </details>

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

* [x] ~metomi-isodatetime~
* [x] cylc-flow
* [x] ~cylc-ui~
* [x] cylc-uiserver
* [x] ~metomi-rose~
* [x] cylc-rose

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* cylc-doc
  * [x] bump intersphinx versions if required (`cylc-doc/src/conf.py`)
  * [x] review [deployment instructions](https://github.com/cylc/cylc-doc#deploying)
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* ~metomi-rose~
  * [x] ~build & deploy documentation (manual process ATM)~
* [x] discourse post

#### Metadata:

GH Actions should automatically open PRs that bump the dev version of the projects. Check and merge them (can push alterations to PR branch if needed).
    
Pin downstream components to the next cylc-flow dev release:
* [ ] cylc-uiserver (pin cylc-flow to next upcoming version)
* [ ] cylc-rose (pin cylc-flow to next upcoming version)
    
Pin components in GH Actions tests:
* [ ] cylc-doc (update versions in `.github/workflows/test.yml` "install libs to document" step(s) as appropriate)
* [ ] metomi-rose (update versions in `.github/actions/install-libs` as appropriate)
    
#### Finally:

* [ ] close this issue :rocket:

**Comment by oliver-sanders** [comment]
### metomi-rose

There are no functional changes against the 2.0.3 or 2.1.0 milestones so there is no need to release either. We can pin cylc-rose against the pre-existing metomi-rose `2.0.*` and cylc-flow `8.1.*`

### cylc-rose

We do not need the `1.1.2` release so we can skip straight to `1.2.0`.

### cylc-uiserver

We do not need the `1.1.1` release so we can skip straight to `1.2.0`.

**Comment by wxtim** [comment]
@oliver-sanders  - any reason why this issue is still open?

**Comment by oliver-sanders** [comment]
The unchecked boxes weren't completed until very recently.
