### ISSUE TITLE
release: 8.2

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-admin#174]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] Ensure all milestones complete.
* [x] All bugfix branches should be merged into master.
* [x] Ensure major changes are listed in cylc-doc (`reference/changes`).
* [x] List the milestones for release below (delete entries as appropriate).

#### Testing:

> Some testing is not fully automated and must be actioned by hand.
    
* [x] Run cylc-flow functional tests against locally available platforms.
* [x] cylc-doc (run a [test build](https://github.com/cylc/cylc-doc/actions/workflows/test.yml)).
* [x] cylc-rose (run the ["tests" action](https://github.com/cylc/cylc-rose/actions/workflows/tests.yml)).
* [x] cylc-uiserver (run the ["test" action](https://github.com/cylc/cylc-uiserver/actions/workflows/test.yml)).
    
#### Milestones for release:

> The release actions close the milestones for you automatically.

- cylc-flow: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/107)](
  https://github.com/cylc/cylc-flow/milestone/107)
- cylc-ui: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/21)](
  https://github.com/cylc/cylc-ui/milestone/21)
- cylc-uiserver: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/14)](
  https://github.com/cylc/cylc-uiserver/milestone/14)
- rose: [![](https://img.shields.io/github/milestones/issues-open/metomi/rose/85)](https://github.com/metomi/rose/milestone/85)
- cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/16)](
  https://github.com/cylc/cylc-rose/milestone/16)
- cylc-doc: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/12)](
  https://github.com/cylc/cylc-doc/milestone/12)

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.
>
> <details>
>   <summary>(logical release order)</summary>
> <pre>R1 = """
>    cylc_flow & metomi_rose => cylc_rose
>    cylc_flow & cylc_ui => cylc_uis
> """</pre>
> </details>

> <details>
>   <summary>Info on version pinning</summary>
>   <br />
>   Cylc plugins (i.e. cylc-rose and cylc-uiserver) are "pinned" to the minor version
>   of cylc-flow. E.G. if the cylc-flow version is 8.1.2 the plugins should be pinned to 8.1.
>   <br /><br />
>   <a href="https://github.com/cylc/cylc-admin/issues/130">More Information</a>
> </details>

* [x] cylc-flow (bump metomi-isodatetime if required)
* [x] cylc-ui
* [x] cylc-uiserver ([update the ui [via GH action](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) first)
* [x] rose
* [x] cylc-rose

#### Forge (check dependencies match):

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> <details>
>   <summary>If the PR doesn't get opened automatically</summary>
>   <br />Create a new branch, change the version, reset the build number and
>   update the hash from the PyPi website.
>   <br />Finally trigger a rerender in a comment.
> </details>

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

* [x] cylc-flow
* [x] ~cylc-ui~ NO!
* [x] cylc-uiserver
* [x] rose
* [x] cylc-rose

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* cylc-doc
  * [x] bump intersphinx versions if required (`cylc-doc/src/conf.py`) https://github.com/cylc/cylc-doc/pull/630
  * [x] review [deployment instructions](https://github.com/cylc/cylc-doc#deploying)
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* metomi-rose
  * [ ] build & deploy documentation (manual process ATM) https://github.com/metomi/rose/pull/2712
* [x] discourse post

#### Metadata:

GH Actions should automatically open PRs that bump the dev version of the projects. Check and merge them (can push alterations to PR branch if needed).

Update cylc-admin with the new branches / meta-release (8.3):
* [x] https://github.com/cylc/cylc-admin/blob/master/docs/status/branches.json
    
Pin downstream components to the next cylc-flow dev release:
* [x] cylc-uiserver (pin cylc-flow to next upcoming version)
* [x] cylc-rose (pin cylc-flow to next upcoming version)
    
Pin components in GH Actions tests:
* [x] cylc-doc (update versions in `.github/workflows/test.yml` "install libs to document" step(s) as appropriate)
    
#### Finally:

* [ ] close this issue :rocket:

**Comment by oliver-sanders** [comment]
Note:

* No metomi-rose release this time (all changes are sync / CI).
* cylc-rose 1.3.0 needs a sync, there is one outstanding issue on 1.2.1, we won't bother releasing 1.2.1 so please scrub this from the changelog.
* Please check all repos are upto sync with bugfix branches.

**Comment by wxtim** [comment]
> No metomi-rose release this time (all changes are sync / CI).

I don't think that this is true: There are a number of fixes against rose 2.0.5 which we do want to release. Additionally Cylc Rose master has assumed that there would be a rose 2.1.0.

**Comment by MetRonnie** [comment]
(Unfortunately we released cylc-rose before noticing it had `metomi-rose==2.1.*`.)

Seeing as there were a couple of bugfixes on the rose 2.0.5 milestone we decided to merge 2.0.x into master and release rose 2.1.0 with those changes

**Comment by MetRonnie** [comment]
This ought to prevent that from happening again: https://github.com/cylc/release-actions/pull/54

**Comment by wxtim** [comment]
> bump intersphinx versions if required

This should have been bumped, but wasn't because the Rose docs aren't ready and changes are minor.
