### ISSUE TITLE
release: 8.3.0

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-admin#193]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] Ensure all milestones complete.
* [x] All bugfix branches should be merged into master.
* [x] Ensure major changes are listed in cylc-doc (`reference/changes`).
* [x] List the milestones for release below (delete entries as appropriate).

#### Testing:

> Some testing is not fully automated and must be actioned by hand.
    
* [x] Run cylc-flow functional tests against locally available platforms.
* [x] cylc-doc (run a [test build](https://github.com/cylc/cylc-doc/actions/workflows/test.yml)) - https://github.com/cylc/cylc-doc/actions/runs/9563076562.
* [x] cylc-rose (run the ["tests" action](https://github.com/cylc/cylc-rose/actions/workflows/tests.yml)) - https://github.com/cylc/cylc-rose/actions/runs/9562550867.
* [x] cylc-uiserver (run the ["test" action](https://github.com/cylc/cylc-uiserver/actions/workflows/test.yml)) - https://github.com/cylc/cylc-uiserver/actions/runs/9564529603.
    
#### Milestones for release:

> The release actions close the milestones for you automatically.

- cylc-flow: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/117)](
  https://github.com/cylc/cylc-flow/milestone/117)
- cylc-ui: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/25)](
  https://github.com/cylc/cylc-ui/milestone/25)
- cylc-uiserver: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/22)](
  https://github.com/cylc/cylc-uiserver/milestone/22)
- metomi/rose: [![](
  https://img.shields.io/github/milestones/issues-open/metomi/rose/96)](
  https://github.com/metomi/rose/milestone/96)
- cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/18)](
  https://github.com/cylc/cylc-rose/milestone/18)
- cylc-doc: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/16)](
  https://github.com/cylc/cylc-doc/milestone/16)

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.
>
> <details>
>   <summary>(logical release order)</summary>
> <pre>R1 = """
>    cylc_flow & metomi_rose => cylc_rose
>    cylc_flow & cylc_ui => cylc_uis
> """</pre>
> </details>

> <details>
>   <summary>Info on version pinning</summary>
>   <br />
>   Cylc plugins (i.e. cylc-rose and cylc-uiserver) are "pinned" to the minor version
>   of cylc-flow. E.G. if the cylc-flow version is 8.1.2 the plugins should be pinned to 8.1.
>   <br /><br />
>   <a href="https://github.com/cylc/cylc-admin/issues/130">More Information</a>
> </details>

* [x] cylc-flow (bump metomi-isodatetime if required)
* [x] cylc-ui
* [x] cylc-uiserver ([update the ui [via GH action](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) first)
* [x] metomi-rose (bump metomi-isodatetime if required)
* [x] cylc-rose

#### Forge (check dependencies match):

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> <details>
>   <summary>If the PR doesn't get opened automatically</summary>
>   <br />Create a new branch, change the version, reset the build number and
>   update the hash from the PyPi website.
>   <br />Finally trigger a rerender in a comment.
> </details>

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

* [x] cylc-flow
* [x] cylc-uiserver
* [x] metomi-rose
* [x] cylc-rose

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* cylc-doc
  * [x] bump intersphinx versions if required (`cylc-doc/src/conf.py`)
  * [x] review [deployment instructions](https://github.com/cylc/cylc-doc#deploying)
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* metomi-rose
  * [x] build & deploy documentation (manual process ATM) - https://github.com/metomi/rose/pull/2792
* Discourse
  * [x] announce the release
  * [ ] scan through the [major changes page](https://cylc.github.io/cylc-doc/stable/html/reference/changes.html)
    and create "tip" posts (linking back to the changes page) to announce any new features.
  * [ ] add a link to interventions docs in response to https://github.com/cylc/cylc-doc/issues/626

#### Metadata:

GH Actions should automatically open PRs that bump the dev version of the projects. Check and merge them (can push alterations to PR branch if needed).
    
Pin downstream components to the next cylc-flow dev release:
* [x] cylc-uiserver (pin cylc-flow to next upcoming version)
* [x] cylc-rose (pin cylc-flow to next upcoming version)
    
#### Finally:

* [ ] close this issue :rocket:

**Comment by oliver-sanders** [comment]
Kicked off cylc-doc test run: https://github.com/cylc/cylc-doc/actions/runs/9562311263/job/26358424632

Expecting failure from the look of the nightlies :(

**Comment by oliver-sanders** [comment]
metomi-rose pypi release appeared to fail with server errors (500 codes) in CI output, however, the release actually succeeded. Ronnie has manually created a GitHub release to match.

**Comment by oliver-sanders** [comment]
Pushed cylc-doc 8.3.0 tag, waiting for metomi-rose docs deployment (required for intersphinx) before deploying cylc-doc.

**Comment by oliver-sanders** [comment]
The two unchecked boxes are about Discourse "tip" announcements which we will trickly through in the coming weeks.

Posted to Element.
