### ISSUE TITLE
release: 8.4.0

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-admin#199]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] List the milestones for release below (delete entries as appropriate).
* [x] All bugfix branches should be merged into master.
* [x] Ensure all milestones complete.
* [x] Ensure major changes are listed in cylc-doc (`reference/changes`).

#### Testing:

> Some testing is not fully automated and must be actioned by hand. Make sure
> the tests for downstream components have been run against the latest
> version of upstream repositories.

* [x] Run cylc-flow functional tests against locally available platforms.
    * [x] Slurm
![image](https://github.com/user-attachments/assets/dd88998e-7989-4c7c-a2fd-859bf5aa536b)
 
* [x] cylc-doc (run a [test build](https://github.com/cylc/cylc-doc/actions/workflows/test.yml)) - [Workflow Run](https://github.com/cylc/cylc-doc/actions/runs/12668639395).
* [x] cylc-rose (run the ["tests" action](https://github.com/cylc/cylc-rose/actions/workflows/tests.yml)) - [Workflow Run](https://github.com/cylc/cylc-rose/actions/runs/12668645726).
* [x] cylc-uiserver (run the ["test" action](https://github.com/cylc/cylc-uiserver/actions/workflows/test.yml)) - [Workflow Run](https://github.com/cylc/cylc-uiserver/actions/runs/12668648751) [![Test](https://github.com/cylc/cylc-uiserver/actions/workflows/test.yml/badge.svg)](https://github.com/cylc/cylc-uiserver/actions/workflows/test.yml)

#### Milestones for release:

> The release actions close the milestones for you automatically.

- cylc-flow: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/125)](
  https://github.com/cylc/cylc-flow/milestone/125)
- cylc-ui: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/27)](
  https://github.com/cylc/cylc-ui/milestone/27)
- cylc-uiserver: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/29)](
  https://github.com/cylc/cylc-uiserver/milestone/29)
- metomi/rose: [![](
  https://img.shields.io/github/milestones/issues-open/metomi/rose/97)](
  https://github.com/metomi/rose/milestone/97)
- cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/22)](
  https://github.com/cylc/cylc-rose/milestone/22)
- cylc-doc: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/18)](
  https://github.com/cylc/cylc-doc/milestone/18)

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.
>
> <details>
>   <summary>(logical release order)</summary>
> <pre>R1 = """
>    metomi_isodatetime => cylc_flow & metomi_rose => cylc_rose
>    cylc_flow & cylc_ui => cylc_uis
> """</pre>
> </details>

> <details>
>   <summary>Info on version pinning</summary>
>   <br />
>   Cylc plugins (i.e. cylc-rose and cylc-uiserver) are "pinned" to the minor version
>   of cylc-flow. E.G. if the cylc-flow version is 8.1.2 the plugins should be pinned to 8.1.
>   <br /><br />
>   <a href="https://github.com/cylc/cylc-admin/issues/130">More Information</a>
> </details>

* [x] metomi-isodatetime
* [x] cylc-flow (bump metomi-isodatetime if required)
* [x] cylc-ui
* [x] cylc-uiserver ([update the ui [via GH action](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) first)
* [x] metomi-rose (bump metomi-isodatetime if required)
* [x] cylc-rose

#### Forge (check dependencies match):

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> <details>
>   <summary>If the PR doesn't get opened automatically</summary>
>   <br />Open a new issue on the feedstock repository, select the
>   "bot command" issue type and set the title to
>   `@conda-forge-admin, please update version`.
> </details>

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

> If you need to make changes, remember to re-render the feedstock
> by commenting `@conda-forge-admin, please rerender` on the PR.

* [x] metomi-isodatetime
* [x] cylc-flow
* [x] cylc-uiserver
* [x] metomi-rose
* [x] cylc-rose

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* metomi-rose
  * [x] build & deploy documentation (manual process ATM)
* cylc-doc
  * [x] bump intersphinx versions if required (`cylc-doc/src/conf.py`)
  * [x] review [deployment instructions](https://github.com/cylc/cylc-doc#deploying)
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* Discourse
  * [x] announce the release
  * [x] scan through the [major changes page](https://cylc.github.io/cylc-doc/stable/html/reference/changes.html)
    and create "tip" posts (linking back to the changes page) to announce any new features.

#### Metadata:

GH Actions should automatically open PRs that bump the dev version of the
projects. Check and merge them (can push alterations to PR branch if needed).

Downstream components will need to have their dependencies bumped:

* [x] cylc-uisever (pin to next minor cylc-flow version)
* [x] cylc-rose (pin to next minor cylc-flow and metomi-rose versions)

#### Finally:

* [x] close this issue :rocket:
