### ISSUE TITLE
Placeholder for 8.0a1 release

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#54]
(feel free to correct the version if it is not 8.0a1)

This issue is to prepare for the 8.0a1 cross component release of Cylc, which should include the following:

- Cylc UI version 0.1: https://github.com/cylc/cylc-ui/milestone/1
  * [x] need a release tag in GitHub for conda recipe, i.e. a release with the zipped dist build for production
  * [x] need an updated git rev in Conda recipe: https://github.com/cylc/cylc-conda/blob/master/recipes/cylc/meta.yaml
- Cylc Flow version 8.0a1: https://github.com/cylc/cylc-flow/milestone/77
  * [x] need a PYPI release (can use test PYPI, we should learn as much as possible from @matthewrmshin, he is the one with most up to date hands-on experience) for the conda recipe
  * [x] need to change the recipe to use the PYPI version instead of building from GitHub: https://github.com/cylc/cylc-conda/blob/master/recipes/cylc-flow/meta.yaml
  * [x] need to confirm if we need to update the metomi-isodatetime recipe to match Cylc Flow requirements: https://github.com/cylc/cylc-conda/blob/master/recipes/metomi-isodatetime/meta.yaml
- Cylc UI Server version 0.1: https://github.com/cylc/cylc-uiserver/milestone/1
  * [x] need a PYPI release: https://github.com/cylc/cylc-uiserver/issues/63
  * [x] need to change the recipe to use the PYPI version instead of building from GitHub: https://github.com/cylc/cylc-conda/blob/master/recipes/cylc-uiserver/meta.yaml
  * [x] need to confirm if we need to update the graphene-tornado recipe to match what Cylc UI Server requires: https://github.com/cylc/cylc-conda/blob/master/recipes/graphene-tornado/meta.yaml
- Cylc Conda recipe:
  * [x] We need to include the configurable-http-proxy now to the recipe https://github.com/cylc/cylc-conda/issues/9 (if too hard, we will ask users to install manually for now)

Some other pending issues that I am not sure if they are a requirement for this 8.0a1 release:

- [x] Do we need to worry about using Conda Forge, or are we going to keep using a channel (everything is in [my personal channel](https://anaconda.org/kinow/repo))
- [x] Do we need the extra cylc-xtriggers now? https://github.com/cylc/cylc-conda/issues/7
  * After chatting with @hjoliver this one doesn't seem to have high priority for now
This is not exactly how the release process should be, so this is not fixing #39 , but I think it will contribute for that issue.

**Comment by kinow** [comment]
@hjoliver I thought this repo would be a good place to log an issue for the cross project release. Hoping this will help us this week when discussing about the next alpha release. I tried to summarize what I think we need.

But I probably have a limited perspective, more biased by my work on Cylc UI. There may be some things missing that are required/expected for this release from other components.

**Comment by kinow** [comment]
(oh, also cylc-flow is matching this release's version, but I believe during the meeting we discussed it, though I don't remember whether we were going to change it or not...)

**Comment by kinow** [comment]
Moved configurable-http-proxy task to the release requirements (as tentantive, with a workaround of installing manually). Still pending forge as we can look at that if we have time, but probably just use my channel. Solved the pending item for `cylc-xtriggers`.

**Comment by wxtim** [comment]
I've also done a bit of PyPi stuff, working with Matt, but it's not something you do ultra often and therefore not something you are going to get ultra familiar with.

**Comment by kinow** [comment]
>I've also done a bit of PyPi stuff, working with Matt, but it's not something you do ultra often and therefore not something you are going to get ultra familiar with.

Same here, and I remember having a few issues the last time I updated (well before they introduced 2FA or tokens). But today in a quick chat with @hjoliver I mentioned we could use this alpha release to generate part of the documentation for #39, maybe documenting how to perform a release for PYPI components under github.com/cylc (probably applicable to metomi components as well)

**Comment by kinow** [comment]
> need to confirm if we need to update the graphene-tornado recipe to match what Cylc UI Server requires: https://github.com/cylc/cylc-conda/blob/master/recipes/graphene-tornado/meta.yaml

Done, it's set to 2.1.1 in the conda-recipe, and we have 2.1.* in the setup.py. Good enough, should work!

**Comment by kinow** [comment]
> need to confirm if we need to update the metomi-isodatetime recipe to match Cylc Flow requirements

Done, all good, 2.0.1 still the latest.

**Comment by kinow** [comment]
Forgot to close this. All done :tada:
